apiVersion: v1
kind: Pod
metadata:
  labels:
    app: __PROJECTNAME__-__ENV__
  name: __PROJECTNAME__-__ENV__

spec:
  containers:
    - image: '__PROJECTNAME__-__ENV__/web'
      name: web
      envFrom: # -> ./ .. /ConfigMap.yaml
        - configMapRef:
            name: __PROJECTNAME__-__ENV__
    #>if is_enabled "${USE_DJANGO}"; then
      volumeMounts:
        - mountPath: /volumes/static
          name: __PROJECTNAME__-__ENV__-static_volume_pvc
        - mountPath: /volumes/media
          name: __PROJECTNAME__-__ENV__-media_volume_pvc
    #>fi

    #>if is_enabled "${USE_DJANGO}"; then
    - image: docker.io/bitnami/mariadb
      name: db
      env:
        - name: MARIADB_ROOT_PASSWORD
          value: rootpassword
        - name: MARIADB_PASSWORD
          value: __PROJECTNAME__password
        - name: MARIADB_USER
          value: __PROJECTNAME__user
        - name: MARIADB_DATABASE
          value: __PROJECTNAME__db
      volumeMounts:
        - mountPath: /bitnami/mariadb
          name: __PROJECTNAME__-__ENV__-db_volume_pvc
    #>fi

    - image: '__PROJECTNAME__-__ENV__/nginx'
      name: nginx
      args:
        - nginx
        - '-g'
        - daemon off;
      ports:
        - containerPort: 9000
          hostPort: __OUTPORT__
      #>if is_enabled "${USE_DJANGO}"; then
      volumeMounts:
        - mountPath: /volumes/media
          name: __PROJECTNAME__-__ENV__-media_volume_pvc
        - mountPath: /volumes/static
          name: __PROJECTNAME__-__ENV__-static_volume_pvc
      #>fi

#>if is_enabled "${USE_DJANGO}"; then
  volumes:
    - name: __PROJECTNAME__-__ENV__-db_volume_pvc
      persistentVolumeClaim:
        claimName: __PROJECTNAME__-__ENV__-db_volume
    - name: __PROJECTNAME__-__ENV__-media_volume_pvc
      persistentVolumeClaim:
        claimName: __PROJECTNAME__-__ENV__-media_volume
    - name: __PROJECTNAME__-__ENV__-static_volume_pvc
      persistentVolumeClaim:
        claimName: __PROJECTNAME__-__ENV__-static_volume
#>fi
